name: Test OIDC Authentication

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  test-oidc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::038462789766:role/GitHubActionsRole
          role-session-name: GitHubActions-Test
          aws-region: us-east-1
          
      - name: Test AWS access
        run: |
          echo "Testing AWS access..."
          aws sts get-caller-identity
          echo "✅ OIDC authentication successful!"
